services:
  - type: web
    name: antivirus-backend
    runtime: dotnet-8
    branch: main
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/ProyectAntivirusBackend.dll
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        sync: false
      - key: Jwt__Audience
        sync: false
      - key: ConnectionStrings__DefaultConnection
        sync: false
