CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE institutions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(255) NOT NULL,
        image text NOT NULL,
        information text,
        CONSTRAINT "PK_institutions" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE opportunity_types (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" character varying(255),
        CONSTRAINT "PK_opportunity_types" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE sectors (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(20) NOT NULL,
        description text,
        CONSTRAINT "PK_sectors" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE services_types (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        name character varying(30) NOT NULL,
        description text,
        CONSTRAINT "PK_services_types" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        fullname character varying(60) NOT NULL,
        email character varying(255) NOT NULL,
        password text NOT NULL,
        phone text,
        rol text NOT NULL,
        registration_date timestamp with time zone NOT NULL,
        birthdate timestamp with time zone NOT NULL,
        is_active boolean NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE opportunities (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        title character varying(255) NOT NULL,
        description text NOT NULL,
        opportunity_type_id integer NOT NULL,
        sector_id integer NOT NULL,
        requirements text,
        benefits text,
        publication_date timestamp with time zone NOT NULL,
        expiration_date timestamp with time zone NOT NULL,
        institution_id integer NOT NULL,
        CONSTRAINT "PK_opportunities" PRIMARY KEY (id),
        CONSTRAINT "FK_opportunities_institutions_institution_id" FOREIGN KEY (institution_id) REFERENCES institutions (id) ON DELETE CASCADE,
        CONSTRAINT "FK_opportunities_opportunity_types_opportunity_type_id" FOREIGN KEY (opportunity_type_id) REFERENCES opportunity_types ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_opportunities_sectors_sector_id" FOREIGN KEY (sector_id) REFERENCES sectors (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE services (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        is_active boolean NOT NULL,
        service_type_id integer NOT NULL,
        title text NOT NULL,
        description text NOT NULL,
        image text NOT NULL,
        CONSTRAINT "PK_services" PRIMARY KEY (id),
        CONSTRAINT "FK_services_services_types_service_type_id" FOREIGN KEY (service_type_id) REFERENCES services_types (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE auth_users (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        password_hash text NOT NULL,
        CONSTRAINT "PK_auth_users" PRIMARY KEY (id),
        CONSTRAINT "FK_auth_users_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE profiles (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        preferences text,
        biography text,
        profile_image text,
        user_id integer NOT NULL,
        CONSTRAINT "PK_profiles" PRIMARY KEY (id),
        CONSTRAINT "FK_profiles_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE TABLE requests (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id integer NOT NULL,
        opportunity_id integer NOT NULL,
        state text NOT NULL,
        request_date timestamp with time zone NOT NULL,
        CONSTRAINT "PK_requests" PRIMARY KEY (id),
        CONSTRAINT "FK_requests_opportunities_opportunity_id" FOREIGN KEY (opportunity_id) REFERENCES opportunities (id) ON DELETE CASCADE,
        CONSTRAINT "FK_requests_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_auth_users_user_id" ON auth_users (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE INDEX "IX_opportunities_institution_id" ON opportunities (institution_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE INDEX "IX_opportunities_opportunity_type_id" ON opportunities (opportunity_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE INDEX "IX_opportunities_sector_id" ON opportunities (sector_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_opportunities_title" ON opportunities (title);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_profiles_user_id" ON profiles (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE INDEX "IX_requests_opportunity_id" ON requests (opportunity_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE INDEX "IX_requests_user_id" ON requests (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE INDEX "IX_services_service_type_id" ON services (service_type_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    CREATE UNIQUE INDEX "IX_users_email" ON users (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250218033714_InitialSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250218033714_InitialSchema', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250220192104_AddPasswordHashToUsers') THEN
    ALTER TABLE users ADD password_hash text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250220192104_AddPasswordHashToUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250220192104_AddPasswordHashToUsers', '9.0.2');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250301223844_SyncSchema') THEN
    ALTER TABLE opportunities DROP CONSTRAINT "FK_opportunities_opportunity_types_opportunity_type_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250301223844_SyncSchema') THEN
    ALTER TABLE opportunity_types RENAME COLUMN "Name" TO name;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250301223844_SyncSchema') THEN
    ALTER TABLE opportunity_types RENAME COLUMN "Description" TO description;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250301223844_SyncSchema') THEN
    ALTER TABLE opportunity_types RENAME COLUMN "Id" TO id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250301223844_SyncSchema') THEN
    ALTER TABLE opportunities ADD status text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250301223844_SyncSchema') THEN
    ALTER TABLE opportunities ADD CONSTRAINT "FK_opportunities_opportunity_types_opportunity_type_id" FOREIGN KEY (opportunity_type_id) REFERENCES opportunity_types (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250301223844_SyncSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250301223844_SyncSchema', '9.0.2');
    END IF;
END $EF$;
COMMIT;

